### ISSUE TITLE
x86 specific flag hardcoded in Makefile prevents building on ARM

### ISSUE THREAD

**Issue by Claus64** [bitshifters/exomizer#1]
Thanks a lot for making the source available! Currently, the Makefile contains "-mtune=i686", which obviously only makes sense for x86 platforms. I was looking for the source code to compile it for ARM and it failed for this reason. Simply removing the switch worked. Is it really needed? Maybe it can be made dependent on `uname -m`, which returns "i686" for compatible platforms?

**Comment by kieranhj** [comment]
Hi, this source does not actually belong to us but originally comes from: https://bitbucket.org/magli143/exomizer/wiki/Home.  I am glad to hear that you have managed to get this compiled for ARM!

**Comment by Claus64** [comment]
Ah I see! I might prepare a proposal for a fix and send it to Magnus Lind then. Thanks a lot!

**Comment by simondotm** [comment]
Aha! It's on bitbucket now - that's great. When I created this repo, the source was only available by zip download on a basic exomizer website, so I reflected it into github just in case the original site disappeared.
